apiVersion: v1
kind: Service
metadata:
  name: weather-api-service
  namespace: weather-api
  labels:
    app: weather-api
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: weather-api
  type: LoadBalancer